controllers/documents_admin.py
from flask import (
    Blueprint, render_template, request, session, flash, url_for, redirect,
    current_app, abort, jsonify
)
from flask_login import login_required, current_user
from controllers.helpers.database import *
from controllers.helpers.password import *
from controllers.helpers.validate_csrf import validate_ajax_csrf
from flask_uploads import UploadSet, IMAGES, ALL
import uuid
from controllers.log_activity import new_activity
import secrets
from datetime import datetime
from flask_mail import Mail, Message
from extension import mail

documents_admin_blueprint = Blueprint('documents_admin', __name__)


@documents_admin_blueprint.route('/documents_admin', methods=['GET', 'POST'])
@login_required
def document_admins():
    if current_user.role != "admin":
        return abort(404)
    if request.method == 'GET':
        session['csrf_token'] = secrets.token_hex(16)
    return render_template(
        'documents_admin.html',
        current_user=current_user,
        csrf_token=session['csrf_token'],
        page_title='Features'
    )


@documents_admin_blueprint.route('/get_scheduled_task', methods=['GET', 'POST'])
@login_required
def get_scheduled_task():
    if current_user.role != "admin":
        return abort(404)
    validate_ajax_csrf()

    sql = "SELECT * FROM schedule_task ORDER BY created_at DESC;"
    try:
        with get_db() as db:
            schedule_task = db.execute(sql).fetchall()
            db.commit()
    except Exception as e:
        print(e)
        schedule_task = []

    data = [
        {
            'name': row[1],
            'description': row[2],
            'created_at': row[3],
            'due_date': row[4],
            'token': row[5]
        }
        for row in schedule_task
    ]

    return jsonify({'data': data})


@documents_admin_blueprint.route('/create_scheduled_task', methods=['GET', 'POST'])
@login_required
def create_scheduled_task():
    json_data = request.get_json()
    validate_ajax_csrf()

    name = json_data['name']
    description = json_data['description']
    created_at = json_data['created_at']
    due_date = json_data['due_date']
    send_schedule_notif = json_data['notif_variable']

    token = str(uuid.uuid4()).replace('-', '')[:7]

    sql = (
        "INSERT INTO schedule_task (name, description, created_at, due_date, token) "
        f"VALUES ('{name}', '{description}', '{created_at}', '{due_date}', '{token}')"
    )
    print(sql)
    try:
        with get_db() as db:
            db.execute(sql)
            db.commit()
        new_activity("created new task")
    except Exception as e:
        print(e)

    if send_schedule_notif:
        get_all_user_email_sql = "SELECT email FROM users WHERE role='pegawai'"
        try:
            with get_db() as db:
                users_email = db.execute(get_all_user_email_sql).fetchall()
                db.commit()
        except Exception as e:
            print(e)
            users_email = []

        email_list = [i[0] for i in users_email]
        print(email_list)

        task_link = url_for('documents_pegawai.upload_document', token=token, _external=True)
        msg = Message('New Task', sender='ivan.spd.com@gmail.com', recipients=email_list)
        msg.html = render_template('email_new_task_template.html', task_link=task_link, name=name)
        mail.send(msg)

    return jsonify({'status': 'success'})


@documents_admin_blueprint.route('/get_task/<token>', methods=['GET'])
@login_required
def get_task(token):
    try:
        with get_db() as db:
            cursor = db.execute(
                "SELECT * FROM schedule_task WHERE token = ?",
                (token,)
            )
            row = cursor.fetchone()
            new_activity("updated task")
        if row:
            return jsonify({
                "status": "success",
                "task": {
                    "name": row[1],
                    "description": row[2],
                    "created_at": row[3],
                    "due_date": row[4],
                    "token": row[5]
                }
            })
        else:
            return jsonify({"status": "error", "message": "Task not found"})
    except Exception as e:
        print(e)
        return jsonify({"status": "error", "message": str(e)})


@documents_admin_blueprint.route('/edit_scheduled_task/<token>', methods=['GET', 'POST'])
@login_required
def edit_scheduled_task(token):
    json_data = request.get_json()
    validate_ajax_csrf()

    name = json_data['name']
    description = json_data['description']
    created_at = json_data['created_at']
    due_date = json_data['due_date']
    send_schedule_notif = json_data['notif_variable']

    sql = (
        "UPDATE schedule_task SET "
        f"name='{name}', description='{description}', "
        f"created_at='{created_at}', due_date='{due_date}' "
        f"WHERE token='{token}'"
    )
    print(sql)
    try:
        with get_db() as db:
            db.execute(sql)
            db.commit()
        new_activity("deleted task")
    except Exception as e:
        print(e)

    if send_schedule_notif:
        get_all_user_email_sql = "SELECT email FROM users WHERE role='pegawai'"
        try:
            with get_db() as db:
                users_email = db.execute(get_all_user_email_sql).fetchall()
                db.commit()
        except Exception as e:
            print(e)
            users_email = []

        email_list = [i[0] for i in users_email]
        print(email_list)

        task_link = url_for('documents_pegawai.upload_document', token=token, _external=True)
        msg = Message('New Task', sender='ivan.spd.com@gmail.com', recipients=email_list)
        msg.html = render_template('email_new_task_template.html', task_link=task_link, name=name)
        mail.send(msg)

    return jsonify({"status": "success"})


@documents_admin_blueprint.route('/delete_schedule_task/<token>', methods=['POST'])
@login_required
def delete_schedule_task(token):
    validate_ajax_csrf()
    try:
        sql = f"DELETE FROM schedule_task WHERE token = '{token}'"
        print(sql)
        with get_db() as db:
            db.execute(sql)
            db.commit()
        return jsonify({"status": "success"})
    except Exception as e:
        print(e)
        return jsonify({"status": "error", "message": str(e)})


@documents_admin_blueprint.route('/details_schedule_task/<token>', methods=['GET', 'POST'])
@login_required
def details_schedule_task(token):
    if request.method == 'GET':
        session['csrf_token'] = secrets.token_hex(16)
    return render_template(
        'detail_schedule_task.html',
        page_title='Features',
        current_user=current_user,
        csrf_token=session['csrf_token'],
        token=token
    )


@documents_admin_blueprint.route('/get_task_users/<token>', methods=['GET'])
@login_required
def get_task_users(token):
    sql = ("SELECT users.id, users.email, COALESCE(NULLIF(task.filename, ''), 'no file') AS filename, COALESCE(NULLIF(task.status, ''), 'Belum Mengunggah') AS status FROM users LEFT JOIN task ON users.id = task.user_id AND task.schedule_task_token = ? WHERE users.role = 'pegawai';")

    with get_db() as db:
        cursor = db.execute(sql, (token,))
        users = cursor.fetchall()
        db.commit()

    print(users)
    users_list = [dict(user) for user in users]
    return jsonify(users_list)


@documents_admin_blueprint.route('/api/task/<token>/<int:user_id>', methods=['PUT'])
@login_required
def update_task_user(token, user_id):
    data = request.json
    status = data.get('status')
    notif_variable_ = data.get('notif_variable_')

    with get_db() as db:
        is_exists_ = db.execute(
            "SELECT * FROM task WHERE schedule_task_token = ? AND user_id = ?", (token, user_id)
        ).fetchone()

        if is_exists_ is None:
            sql_insert = (
                "INSERT INTO task (schedule_task_token, user_id, status) "
                "VALUES (?, ?, ?);"
            )
            cursor = db.execute(sql_insert, (token, user_id, status))
            db.commit()
            if cursor.rowcount == 0:
                return jsonify({'status': 'error', 'message': 'User not found'}), 404
        else:
            sql_update = (
                "UPDATE task SET status = ? WHERE schedule_task_token = ? AND user_id = ?"
            )
            cursor = db.execute(sql_update, (status, token, user_id))
            db.commit()

    if notif_variable_ == 1:
        get_all_user_email_sql = "SELECT email FROM users WHERE role='pegawai' AND id = ?"
        try:
            with get_db() as db:
                users_email = db.execute(get_all_user_email_sql, (user_id,)).fetchall()
                db.commit()
        except Exception as e:
            print(e)
            users_email = []

        email_list = [i[0] for i in users_email]
        print(email_list)

        task_link = url_for('views.dashboard', _external=True)
        msg = Message('Update Status', sender='ivan.spd.com@gmail.com', recipients=email_list)
        msg.html = render_template('email_update_task_template.html', task_link=task_link)
        mail.send(msg)

    if cursor.rowcount == 0:
        return jsonify({'status': 'error', 'message': 'User not found'}), 404

    return jsonify({'status': 'success'})


@documents_admin_blueprint.route('/master_admin', methods=['GET', 'POST'])
@login_required
def master_admin():
    if request.method == 'GET':
        session['csrf_token'] = secrets.token_hex(16)
    return render_template(
        'master_admin.html',
        current_user=current_user,
        csrf_token=session['csrf_token'],
        page_title='Master Admin'
    )


@documents_admin_blueprint.route('/get_users', methods=['GET'])
@login_required
def get_users():
    with get_db() as db:
        cursor = db.execute('SELECT id, name, email, role FROM users')
        users = cursor.fetchall()
        db.commit()

    print(users)

controllers/settings_profile.py
from flask import (
    Blueprint, render_template, request, session, flash, url_for, redirect, current_app
)
from flask_login import login_required, current_user
from controllers.helpers.database import *
from controllers.helpers.password import *
from flask_uploads import UploadSet, IMAGES
import os
import uuid
from controllers.log_activity import new_activity

avatars = UploadSet('avatars', IMAGES)
settings_profile_blueprint = Blueprint('settings_profile', __name__)

def get_random_filename(filename):
    ext = os.path.splitext(filename)[1]
    return f"{uuid.uuid4().hex}{ext}"

@settings_profile_blueprint.route('/update_public_info', methods=['GET', 'POST'])
@login_required
def update_public_info():
    if request.method == 'POST':
        if request.form.get('csrf_token') != session.get('csrf_token'):
            flash('Invalid Token!', 'error')
            return redirect(url_for('views.settings'))

        username = request.form.get('username')
        biography = request.form.get('biography')
        profile_pict = request.files.get('avatar')

        # Log aktivitas jika ada perubahan
        if username != current_user.username:
            new_activity("updated username")
        if biography != current_user.biography:
            new_activity("updated biography")

        update_fields = []
        params = []

        # Update username dan biography
        fields = {
            'username': username,
            'biography': biography
        }
        for field, value in fields.items():
            update_fields.append(f"{field} = ?")
            params.append(value)

        # Handle upload avatar
        if profile_pict:
            profile_pict.seek(0, os.SEEK_END)
            size = profile_pict.tell()
            profile_pict.seek(0)
            if size > 5 * 1024 * 1024:
                flash('Max file size is 5MB', 'error')
                return redirect(url_for('views.settings'))
            try:
                filename = get_random_filename(profile_pict.filename)
                filename = avatars.save(profile_pict, name=filename)
                new_activity("updated avatar")
                update_fields.append('profile_pict = ?')
                params.append(filename)
                # Hapus avatar lama jika ada
                if current_user.profile_pict:
                    old_avatar_path = os.path.join('static', 'uploads', 'avatars', current_user.profile_pict)
                    if os.path.exists(old_avatar_path):
                        os.remove(old_avatar_path)
            except Exception:
                flash('Failed to upload profile pict', 'error')
                return redirect(url_for('views.settings'))

        # Update data jika ada perubahan
        if update_fields:
            sql = f"UPDATE users SET {', '.join(update_fields)} WHERE id = ?"
            params.append(current_user.id)
            try:
                with get_db() as db:
                    db.execute(sql, params)
                    db.commit()
                flash('Successfully updated your public info.', 'success')
            except Exception as e:
                flash('Failed to update your public info. ' + str(e), 'error')
                return redirect(url_for('views.settings'))
        else:
            flash('No changes to update.', 'info')

    return redirect(url_for('views.settings'))


@settings_profile_blueprint.route('/update_private_info', methods=['GET', 'POST'])
@login_required
def update_private_info():
    if request.method == 'POST':
        if request.form.get('csrf_token') != session.get('csrf_token'):
            flash('Invalid Token!', 'error')
            return redirect(url_for('views.settings'))

        name = request.form.get('name')
        phone_number = request.form.get('phone_number')

        # Log aktivitas jika ada perubahan
        if name != current_user.name:
            new_activity("updated name")
        if phone_number != current_user.phone_number:
            new_activity("updated phone number")

        update_fields = []
        params = []

        fields = {
            'name': name,
            'phone_number': phone_number
        }
        for field, value in fields.items():
            update_fields.append(f"{field} = ?")
            params.append(value)

        if update_fields:
            sql = f"UPDATE users SET {', '.join(update_fields)} WHERE id = ?"
            params.append(current_user.id)
            try:
                with get_db() as db:
                    db.execute(sql, params)
                    db.commit()
                flash('Successfully updated your private info.', 'success')
            except Exception as e:
                flash('Failed to update your private info. ' + str(e), 'error')
                return redirect(url_for('views.settings'))
        else:
            flash('No changes to update.', 'info')

    return redirect(url_for('views.settings'))


@settings_profile_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    if request.method == 'POST':
        if request.form.get('csrf_token') != session.get('csrf_token'):
            flash('Invalid Token!', 'error')
            return redirect(url_for('views.settings'))

        current_password = request.form['current_password']
        new_password = request.form['new_password']
        verify_password_field = request.form['verify_password']

        if current_password and new_password and verify_password_field:
            if not verify_password(current_user.password_hash, current_password):
                flash('Current password is incorrect.', 'error')
                return redirect(url_for('views.settings'))

            if new_password != verify_password_field:
                flash('New passwords do not match.', 'error')
                return redirect(url_for('views.settings'))

            hashed_new_password = hash_password(new_password)
            sql = f"UPDATE users SET password_hash = ? WHERE id = ?"
            try:
                with get_db() as db:
                    db.execute(sql, (hashed_new_password, current_user.id))
                    db.commit()
                flash('Successfully updated your password.', 'success')
            except Exception as e:
                flash('Failed to update your password. ' + str(e), 'error')
                return redirect(url_for('views.settings'))
        else:
            flash('All fields must be filled.', 'error')

    return redirect(url_for('views.settings'))

templates/documents_pegawai.html
{% include "partials/main_head.html" %} {% include "partials/alert.html" %}
<main class="content">
  <div class="container-fluid p-0">
    <div class="mb-3">
      <h1 class="h3 d-inline align-middle">Task History</h1>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title"></h5>
          </div>
          <div class="card-body">
            <br />
            <div class="m-1 pb-5" style="overflow: auto">
              <table
                id="datatables_all_history_task"
                class="table table-striped dataTable no-footer table-bordered"
                style="width: 100%"
              >
                <thead>
                  <tr>
                    <th>Token</th>
                    <th>Filename</th>
                    <th>Status</th>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
<!-- Modal -->
<div
  class="modal fade"
  id="taskDetailModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Jadwal Tugas</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <label class="form-label">Status</label>
          <input type="text" class="form-control" id="taskStatus" disabled />
        </div>
        <div class="mb-3">
          <label class="form-label">Filename</label>
          <input id="taskFilename" type="text" class="form-control" disabled />
        </div>
        <div class="mb-3">
          <a class="btn btn-primary" id="downloadLink" role="button"
            ><i class="fa-solid fa-download"></i
          ></a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>
{% include "partials/main_foot.html" %}

templates/profile_settings.html
{% include "partials/main_head.html" %} {% include "partials/alert.html" %}
<main class="content">
    <div class="container-fluid p-0">
        <h1 class="h3 mb-3">Settings</h1>
        <div class="row">
            <div class="col-md-3 col-xl-2">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Profile Settings</h5>
                    </div>
                    <div class="list-group list-group-flush" role="tablist">
                        <a
                            class="list-group-item list-group-item-action active"
                            data-bs-toggle="list"
                            href="#account"
                            role="tab"
                            aria-selected="true"
                        >
                            Account
                        </a>
                        <a
                            class="list-group-item list-group-item-action"
                            data-bs-toggle="list"
                            href="#password"
                            role="tab"
                            aria-selected="false"
                            tabindex="-1"
                        >
                            Password
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-9 col-xl-10">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="account" role="tabpanel">
                        <div class="card" style="overflow: auto">
                            <div class="card-header">
                                <h5 class="card-title mb-0">Public info</h5>
                            </div>
                            <div class="card-body">
                                <form method="post" action="{{url_for('settings_profile.update_public_info')}}" enctype="multipart/form-data">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="mb-3">
                                                <label class="form-label" for="inputUsername">
                                                    Username
                                                </label
                        >
                                                <input
                                                    name="username"
                                                    type="text"
                                                    class="form-control"
                                                    id="inputUsername"
                                                    placeholder="Username"
                                                    value="{{current_user.username or ''}}"
                                                >
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label" for="inputUsername">
                                                    Biography
                                                </label
                        >
                                                <textarea
                                                    name="biography"
                                                    rows="2"
                                                    class="form-control"
                                                    id="inputBio"
                                                    placeholder="Tell something about yourself"
                                                >{{current_user.biography  or ''}}</textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="text-center">
                                                <img
                                                    alt="Profile Pict"
                                                    src="{{ url_for('static', filename='uploads/avatars/'+(current_user.profile_pict or 'default.jpg'))}}"
                                                    class="rounded-circle img-responsive mt-2"
                                                    width="128"
                                                    height="128"
                                                    id="profile_pic_frame"
                                                >
                                                <div class="mt-2">
                                                    <input
                                                        type="file"
                                                        name="avatar"
                                                        id="avatar"
                                                        style="display: none"
                                                        accept="image/*"
                                                    >
                                                    <label for="avatar" class="btn btn-primary" style="cursor: pointer">
                                                        <i class="fas fa-upload"></i>
                                                        Upload
                                                    </label>
                                                </div>
                                                <small>
                                                    For best results, use an image at least 128px by 128px
                          in .jpg format
                                                </small>
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">
                                        Save changes
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title mb-0">Private info</h5>
                            </div>
                            <div class="card-body">
                                <form method="post" action="{{url_for('settings_profile.update_private_info')}}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                                    <div class="mb-3">
                                        <label class="form-label" for="inputFullName">
                                            Full Name
                                        </label
                      >
                                        <input
                                            name="name"
                                            type="text"
                                            class="form-control"
                                            id="inputFulltName"
                                            placeholder="Full name"
                                            value="{{current_user.name or ''}}"
                                        >
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label" for="inputEmail4">Email</label>
                                        <input
                                            type="email"
                                            class="form-control"
                                            id="inputEmail4"
                                            placeholder="Email"
                                            name="email"
                                            value="{{current_user.email}}"
                                            disabled
                                        >
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label" for="inputAddress">Phone Number</label>
                                        <input
                                            type="number"
                                            class="form-control"
                                            id="inputPhone"
                                            placeholder="Input your phone number"
                                            name="phone_number"
                                            value="{{current_user.phone_number or ''}}"
                                        >
                                    </div>
                                    <button type="submit" class="btn btn-primary">
                                        Save changes
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="password" role="tabpanel">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Password</h5>
                                <form method="post" action="{{url_for('settings_profile.update_password')}}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                                    <div class="mb-3">
                                        <label class="form-label" for="inputPasswordCurrent">
                                            Current password
                                        </label
                    >
                                        <input
                                            type="password"
                                            class="form-control"
                                            name="current_password"
                                            id="inputPasswordCurrent"
                                        >
                                        <small>
                                            <a href="#">Forgot your password?</a>
                                        </small>
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label" for="inputPasswordNew">
                                            New password
                                        </label
                    >
                                        <input
                                            type="password"
                                            class="form-control"
                                            id="inputPasswordNew"
                                            name="new_password"
                                        >
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label" for="inputPasswordNew2">
                                            Verify password
                                        </label
                    >
                                        <input
                                            type="password"
                                            class="form-control"
                                            id="inputPasswordNew2"
                                            name="verify_password"
                                        >
                                    </div>
                                    <button type="submit" class="btn btn-primary">
                                        Save changes
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<script>
  const avatarInput = document.getElementById("avatar");
  const avatarPreview = document.getElementById("profile_pic_frame");
  avatarInput.addEventListener("change", function () {
    const file = this.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        avatarPreview.src = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  });
</script>
{% include "partials/main_foot.html" %}